// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    
		int n = Integer.parseInt(args[0]);
	
		int smallerThen = 0;
		int biggerThen = 0;
		

		for (int i = 0; i < n; i++) {

			double x = Math.random();

				if (x <= 0.5) {
					smallerThen++;
				} else {
					biggerThen++;
				}

		}

		double ratio;

			if (smallerThen == 0) {
				System.out.println("> 0.5: " + biggerThen + " times");
				System.out.println("<= 0.5: " + smallerThen + " times");
			} else {
				ratio = (double) biggerThen / smallerThen;
				System.out.println("> 0.5: " + biggerThen + " times");
				System.out.println("<= 0.5: " + smallerThen + " times");
				System.out.println("Ratio: " + ratio);
			}


	}
}
